/* This file was generated by r.out.leaflet GRASS GIS module. */

var layerInfos = [
   {title: "captblinky_sound1", file: "captblinky_animation_0000_Layer-15.png", bounds: [[24.31,-80.75], [24.73,-82.25]], opacity: 1.0}
,   {title: "captblinky_sound2", file: "captblinky_animation_0001_Layer-14.png", bounds: [[24.31,-80.75], [24.73,-82.25]], opacity: 1.0}
,   {title: "captblinky_sound3", file: "captblinky_animation_0002_Layer-13.png", bounds: [[24.31,-80.75], [24.73,-82.25]], opacity: 1.0}
,   {title: "captblinky_sound4", file: "captblinky_animation_0003_Layer-12.png", bounds: [[24.31,-80.75], [24.73,-82.25]], opacity: 1.0}
,   {title: "captblinky_sound5", file: "captblinky_animation_0004_Layer-11.png", bounds: [[24.31,-80.75], [24.73,-82.25]], opacity: 1.0}
,   {title: "captblinky_sound6", file: "captblinky_animation_0005_Layer-10.png", bounds: [[24.31,-80.75], [24.73,-82.25]], opacity: 1.0}
,   {title: "captblinky_sound7", file: "captblinky_animation_0006_Layer-9.png", bounds:  [[24.31,-80.75], [24.73,-82.25]], opacity: 1.0}
,   {title: "captblinky_sound8", file: "captblinky_animation_0007_Layer-8.png", bounds: [[24.31,-80.75], [24.73,-82.25]], opacity: 1.0}
,   {title: "captblinky_sound9", file: "captblinky_animation_0008_Layer-7.png", bounds: [[24.31,-80.75], [24.73,-82.25]], opacity: 1.0}
,   {title: "captblinky_sound10", file: "captblinky_animation_0009_Layer-6.png", bounds: [[24.31,-80.75], [24.73,-82.25]], opacity: 1.0}
,   {title: "captblinky_sound11", file: "captblinky_animation_0010_Layer-5.png", bounds: [[24.31,-80.75], [24.73,-82.25]], opacity: 1.0}
,   {title: "captblinky_sound12", file: "captblinky_animation_0011_Layer-4.png", bounds: [[24.31,-80.75], [24.73,-82.25]], opacity: 1.0}
,   {title: "captblinky_sound13", file: "captblinky_animation_0012_Layer-3.png", bounds: [[24.31,-80.75], [24.73,-82.25]], opacity: 1.0}
,   {title: "captblinky_sound14", file: "captblinky_animation_0013_Layer-2.png", bounds: [[24.31,-80.75], [24.73,-82.25]], opacity: 1.0}
,   {title: "captblinky_sound15", file: "captblinky_animation_0014_Layer-1.png", bounds: [[24.31,-80.75], [24.73,-82.25]], opacity: 1.0}
];
